@Library("shared") _
pipeline{
    agent {label "dev"};
    stages{
        stage("Code"){
            steps{
                script {
                clone("https://github.com/satinderkaura348-ops/community_portfolio.git", "main")
                }
            }
        }
        stage("Trivy Test"){
            steps{
                script{
                    trivy_fs
                }
            }
        }
        stage("Build"){
            steps{
                sh "docker build -t community-app ."
            }
        }
        stage("Test"){
            steps{
                echo "To be confirmed by developer"
            }
        }
        stage("Push to docker hub"){
            steps{
                script{
                    docker_push("dockerHubCreds", "portfolio-app")
                }
            }
        }
        stage("Deploy"){
            steps{
                sh "docker-compose up -d"
            }
        }
    }
    
post{
    success{
        script{
            emailext from: 'satinder42020@gmail.com',
            to: 'satinder42020@gmail.com',
            body: 'Build successful for CICD portfolio app',
            subject: 'Build successful for CICD portfolio app'
        }
    }
    failure{
        script{
            emailext from: 'satinder42020@gmail.com', 
            to: 'satinder42020@gmail.com',
            body: 'Build Failed for CICD portfolio app',
            subject: 'Build Failed for CICD portfolio app'
        }
    }
}    
}


