apiVersion: v1
kind: Service

metadata:
  name: portfolio-svc
  namespace: portfolio-ns


spec:
  selector:
    app: portfolio

  ports:
    - protocol: TCP
      port: 82      # host port
      targetPort: 3000  #container port
