kind: Service
apiVersion: v1

metadata:
  name: online-shop-svc
  namespace: online-shop

spec:
  selector:
    app.kubernetes.io/name: online-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
