kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: mysql-pvc
  namespace: mysql

spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
